const error = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_PASSWORD_NOTCORRECT: 'USER_PASSWORD_NOTCORRECT',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};

module.exports = {
    error,
};
