const error = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_PASSWORD_NOTCORRECT: 'USER_PASSWORD_NOTCORRECT',
    USERROLE_NOT_FOUND: 'USERROLE_NOT_FOUND',
    USERROLE_REFERENCES_WITH_USER: 'USERROLE_REFERENCES_WITH_USER',
    USERROLE_ALREADY_EXISTS: 'USERROLE_ALREADY_EXISTS',
    THIS_NOT_BRANCH: 'THIS_NOT_BRANCH',
    BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
    BRANCH_POST_ERROR: 'BRANCH_POST_ERROR',
    BRANCH_EDIT_ERROR: 'BRANCH_EDIT_ERROR',
    BRANCH_DELETE_ERROR: 'BRANCH_DELETE_ERROR',
    BRANCH_NAME_NOT_FOUND: 'BRANCH_NAME_NOT_FOUND',
    BRANCH_NAME_ALREADY_EXIST: 'BRANCH_NAME_ALREADY_EXIST',
    VALIDATION_ERROR_BRANCH_UUID: 'VALIDATION_ERROR_BRANCH_UUID',
    VALIDATION_ERROR_BRANCH_STRING: 'VALIDATION_ERROR_BRANCH_STRING',
    VALIDATION_ERROR_BRANCHNAME_LENGTH: 'VALIDATION_ERROR_BRANCHNAME_LENGTH',
    VALIDATION_ERROR_BRANCHNAME_EXIST: 'VALIDATION_ERROR_BRANCHNAME_EXIST',
    VALIDATION_ERROR_BRANCHNAME_REQUIRED: 'VALIDATION_ERROR_BRANCHNAME_REQUIRED',
    UPLOAD_ERROR: 'UPLOAD_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = {
    error,
};
