const error = {
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_PASSWORD_NOTCORRECT: 'USER_PASSWORD_NOTCORRECT',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
}

module.exports = {
    error
}